# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('now', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='pop', max_length=1000),
            preserve_default=False,
        ),
    ]
